name: Deploy
on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Tar
        run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf deploy.tar ../build/
      - name:
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "deploy.tar"
          target: "/root/ShoppingListGenerator/main.py"