name: Deploy
on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name:
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "main.py"
          target: "/root/ShoppingListGenerator/main.py"