name: Deploy
on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Tar
        run: |
          pwd
          mkdir ../build
          cp -TR . ../build
          tar -cvf deploy.tar ../build/
      - name: SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "deploy.tar"
          target: "/root/ShoppingListGenerator"
      - name: Cleanup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /root/ShoppingListGenerator
            rm main.py
            tar -xf deploy.tar
            rm deploy.tar
            mv build/main.py main.py
            rm -r build